import Navigation from "@/components/navigation/Navigation"
import '@/assets/SCSS/style.scss'
import '@/assets/SCSS/styleTheme.scss'
import ThemeProvider from "@/contexts/ThemeProvider"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navigation />

          <main>
            { children }
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}