import '@/assets/SCSS/styleNotFoundPage.scss'
import Link from 'next/link'

export const metadata = {
    title: "Error Page",
    description: 'Generated by create next app',
}

export default function NotFound() {
    return (
        <div className="not-found-page">
            <h1>404: Page not found!</h1>
            <p>Please return to home page.</p>
            <Link href={'/'}>Home</Link>
        </div>
    )
}
