import AvataImage from "./components/AvataImage"
import Link from "next/link"
import '@/assets/SCSS/stylePortfolioPage.scss'

export const metadata = {
    title: "Exercise Portfolio",
    description: 'Generated by create next app',
}

export default function Portfolio() {
    const listSocialContact = [
        {
            name: "Phone: ",
            info: "0328895451",
            href: "/",
        },
        {
            name: "Zalo: ",
            info: "https://zalo.me",
            href: "https://zalo.me",
        },
        {
            name: "Email: ",
            info: "contact@fullstack.edu.vn",
            href: "mailto:contact@fullstack.edu.vn",
        },
        {
            name: "Facebook: ",
            info: "https://www.facebook.com/groups/f8official",
            href: "https://www.facebook.com/groups/f8official",
        },
        {
            name: "Youtube: ",
            info: "https://www.youtube.com/c/f8vnofficial",
            href: "https://www.youtube.com/c/f8vnofficial",
        },
    ]

    return (
        <div className='portfolio-page'>
            <div className="container">
                <h1>The Example Name</h1>

                <div className="separate-column">
                    <aside className="overral">
                        <figure>
                            <AvataImage />
                            <figcaption className='desc'>Frond-end developer</figcaption>
                        </figure>

                        <div className="skills">
                            <h3>My skills</h3>
                            <p><span>Web developer</span>:  REST API, React.js, Next.js, Redux, Context, CSS3, HTML5, UI/UX, Figma, Photoshop...</p> 
                            <p><span>Other skills</span>:  Relatively good research and search skills. Working thinking, good teamwork skills...</p>

                            <h3>Histories</h3>
                            <p><span>2015</span>:  One of junior high school</p>
                            <p><span>2016-2018</span>:  Other Junior high school</p>
                            <p><span>2018-2020</span>:  Other high school</p>
                            <p><span>2021-2023</span>:  College studies</p>
                        </div>
                    </aside>

                    <div className='info'>
                        <div className='contact'>
                            <h3 className='contact-heading'>Social contact</h3>
                            {
                                listSocialContact.map(({ name, info, href }, index) => {
                                    if (index === 0) {
                                        return (
                                            <p className='contact-social' key={index}>
                                                <span>{ name }</span>
                                                <Link href={href}>{info}</Link>
                                            </p>
                                        )
                                    }
                                    return (
                                        <p className='contact-social' key={index}>
                                            <span>{ name }</span>
                                            <a href={href} target="_blank">{info}</a>
                                        </p>
                                    )
                                })
                            }
                        </div>

                        <div className='projects'>
                            <h3>Self project</h3>

                            <div className='project'>
                                <h4>Project GreenChop</h4>
                                <p>A simple project completed in 4 days</p>
                                <p>A simple website to promote products for a company built with HTML SCSS</p>
                                <div className='action-buttons'>
                                    <a href="https://phivanduc.github.io/Offline-F8-K3/Project-FrontEnd/" target="_blank">Demo</a>
                                    <a href="https://github.com/PhiVanDuc/Offline-F8-K3/tree/main/Project-FrontEnd" target="_blank">Code</a>
                                </div>
                            </div>

                            <div className='project'>
                                <h4>Project Mini Trello</h4>
                                <p>A more complex project is completed in 1 week</p>
                                <p>A task management application that can arbitrarily arrange the order of tables and tasks built with ReactJS</p>
                                <div className='action-buttons'>
                                    <a href="https://phivanduc.github.io/Offline-F8-K3/Day-47-React/dist/" target="_blank">Demo</a>
                                    <a href="https://github.com/PhiVanDuc/Offline-F8-K3/tree/main/Day-47-React" target="_blank">Code</a>
                                </div>
                            </div>

                            <a href="https://github.com/PhiVanDuc/Offline-F8-K3" target="_blank">https://github.com/PhiVanDuc/Offline-F8-K3</a>
                        </div>

                        <div className='hobbies'>
                            <h3>My hobbies</h3>

                            <ul className='list-hobbies'>
                                <li className='hobby'>Enjoy Relaxing Music, gentle songs, like piano and jazz...</li>
                                <li className='hobby'>Read Books, Learn More About New Programming Languages. Currently, I Am Self-Studying NextJS</li>
                                <li className='hobby'>Follow The Technology Trends, News About Famous Products Like Macbook, Samsung, Asus, ...</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}